Add github-pages for documentation
LAM-GeMont/fehlzeiten pull request #134
Opened 2021-12-02 01:32 UTC by jonaslanglotz

@bucherfa suggested we use github-pages for the documentation of the app. To facilitate this, I have prepared a basic setup. Should we replace the filler text before we merge?

2021-12-02 09:52 UTC, bucherfa commented
yeah, I think I will prepare some more stuff, at least like an idea for the structure.

2021-12-02 17:54 UTC, bucherfa approved these changes, later dismissed
jetzt können wir es gerne mergen. Hab die doku mal grob umrissen.

habe mich mal als codeowner für das Verzeichnis `/docs` eingetragen, damit ich das an euch vorbeischleusen kann.

2021-12-03 15:49 UTC, EricZimmer1 requested changes
Zwei kleine Sachen. Ansonsten sieht’s top aus

2021-12-03 15:49 UTC, EricZimmer1 commented on docs/navigation.md
> +Um zwischen den Tätigkeiten zu wechseln, kann die Navigationsleiste entweder auf der linken Seite den Bildschirm oder unten am Bildschirm verwendet werden.
Eventuell besser: „auf der linken Seite des Bildschirms oder am unteren Bildschirmrand …“

2021-12-03 15:49 UTC, EricZimmer1 commented on docs/navigation.md
> +Sollte sich die Navigationsleiste am unteren Bildschirmrand befinden, könnte es sein, dass man die Leiste <b>horizontal Bewegen</b> kann.
Vielleicht sollten wir uns auf eine Ansprache festlegen. Also entweder Sie müssen das und das machen oder etwas muss gemacht werden

2021-12-03 16:00 UTC, bucherfa commented
@EricZimmer1 angepasst. Ich denke, dass wir mit einer generellen Schreibform weitermachen werden.

2021-12-03 16:56 UTC, EricZimmer1 approved these changes

2021-12-03 17:33 UTC, merged