absence: add exam attribute to Absence entity
LAM-GeMont/fehlzeiten pull request #60
Opened 2021-11-22 10:35 UTC by bucherfa

* extend mutation by exam attribute
* extend frontend by exam attribute

2021-11-22 22:17 UTC, jonaslanglotz requested changes
Sieht gut aus soweit, nur nochmal die Variablen nachbessern 👍

2021-11-22 22:17 UTC, jonaslanglotz commented on web/src/pages/absence.tsx
> +                <FormControl isInvalid={form.errors.lesson && form.touched.lesson} mb={6} display="flex" alignItems="center">
Hier müsste `form.exams` abgefragt werden

2021-11-23 09:16 UTC, bucherfa commented on web/src/pages/absence.tsx
> +                <FormControl isInvalid={form.errors.lesson && form.touched.lesson} mb={6} display="flex" alignItems="center">
angepasst

2021-11-23 12:36 UTC, jonaslanglotz approved these changes

2021-11-23 16:39 UTC, merged